Work kaogon
JavaJava19/jps.gg pull request #69
Opened 2023-06-14 15:37 UTC by kaogon128

## ⛏ 変更内容 / Details of Changes
フォーラム向けのログイン機構

2023-06-14 15:54 UTC, yui-Kitamura commented on source/src/components/page/Login.js
> +        <div onClick={(e) => Login(e)}> Login</div>
input type="submit" を使って form のonSubmitを発火させませんか？

2023-06-14 16:04 UTC, graycat27 commented on source/src/components/parts/top/Hamburger.js
> +        } else {
if(cookie){ }  
if(ssnStrg){ }  
の2段構成にせず、elseに入れてるのは訳あり？

2023-06-14 16:04 UTC, graycat27 commented on source/src/components/parts/top/LoginStatusParts.js
> +              top: "-52px",
レスポンシブするissueは別立て？

2023-06-14 16:07 UTC, kaogon128 commented on source/src/components/parts/top/Hamburger.js
> +        } else {
チェックボックスでクッキー使うか否かでクッキーに入れるかセッションストレージにいれるかってやってるから
どっちかにしか入らないしelseでいいかな？ってｗ
念のため２段構成にしたほうがよきですかね？
一応どちらかにトークンをもってログインページに飛ぶとトップに飛ぶ仕様にはなってます！

2023-06-14 16:13 UTC, graycat27 commented on source/src/components/parts/top/Hamburger.js
> +        } else {
もしかして：ラジオボタン  
その選択仕様に依存するのはなんだかなぁ、と思ってしまう  
あと、入れ子が深くなるのも好きくない

2023-06-14 16:14 UTC, kaogon128 commented on source/src/components/parts/top/LoginStatusParts.js
> +              top: "-52px",
あ、スマホサイズか否かでサイズ調整してました…w

2023-06-14 16:15 UTC, kaogon128 commented on source/src/components/parts/top/Hamburger.js
> +        } else {
なるほどｂｂ
じゃあ２段式にします！ｗ

2023-06-16 14:22 UTC, graycat27 requested changes
ちょこちょこ確認お願いします

2023-06-16 14:22 UTC, graycat27 commented on source/src/components/page/Login.js
> +            <label htmlFor='check'>入力したデータをクッキーに保存しておく</label>
クッキーはIT用語としてCookieにしておきたい  
[MDN Cookie](https://developer.mozilla.org/ja/docs/Web/HTTP/Cookies)
> HTTP Cookie (ウェブ Cookie、ブラウザー Cookie) は、...

2023-06-16 14:22 UTC, graycat27 commented on source/src/components/page/Login.js
> +            <input type='submit' onClick={(e) => Login(e)} value={"Login"} />
submitで<form>のonSubmitが発火するのでLogin(e)が多重発火しない？

2023-06-16 14:22 UTC, graycat27 commented on source/src/components/parts/top/Hamburger.js
> +                                <div className={style.Link} onClick={() => jump("/contact")}>Contact</div>
気づかんかった..  
修正ヨシ！

2023-06-16 14:22 UTC, graycat27 commented on source/src/css/login.module.css
> +    border-bottom: 1px solid #777;
`#777` と L16 での `#777777` の揺れが気になるにゃ

2023-06-16 14:22 UTC, graycat27 commented on source/src/css/login.module.css
> +    background-color: rgb(216, 233, 248);
`#d8e9f8`

2023-06-16 14:22 UTC, graycat27 commented on source/src/css/login.module.css
> +        width: 100%;
vhを使うならこっちもvwでいいかも

2023-06-16 14:22 UTC, graycat27 commented on source/src/css/login.module.css
> +    }
ついに1スタイルの中で`#777`と`#777777` を共存させましたね

2023-06-16 14:22 UTC, graycat27 commented on source/src/components/util/LoginUtil.js
> +                ).catch(console.log)
![image](https://github.com/JavaJava19/jps.gg/assets/64903817/3e5f8194-7c92-430d-bc7d-fd5f60d02666)
せっかくなので

2023-06-16 14:23 UTC, graycat27 commented on source/src/components/parts/top/Hamburger.js
> +        } else {
fixed

2023-06-17 23:44 UTC, graycat27 approved these changes

2023-06-17 23:44 UTC, merged